### ISSUE TITLE
Global filter ignore rule by file name

### ISSUE THREAD

**Issue by mihaisoloi** [ghik/silencer#19]
For now the global filters ignore by error message patterns

`scalacOptions += "-P:silencer:globalFilters=[semi-colon separated message patterns]"`

it would be great if we could ignore by file name patterns as well.

This way we could handle issues where the compiler is used to generate some classes. An issue you can't use the `silencer` for is this:
https://github.com/playframework/playframework/issues/7382

**Comment by ghik** [comment]
Fixed in 1.3.0
