### ISSUE TITLE
Fail to silent with `sbt unidoc`

### ISSUE THREAD

**Issue by manuzhang** [ghik/silencer#22]
I've tried to silent warnings like `private default argument in object GroupByOp is never used`. It works in `sbt compile` but fails with `sbt unidoc` (https://github.com/sbt/sbt-unidoc)

silencer version: 1.3.1
unidoc version: 0.4.2

**Comment by ghik** [comment]
I could not reproduce this on my own project which uses both silencer and unidoc. This is most likely a build setup issue within your project - `silencer-plugin` is likely not added to compiler options used by the `unidoc` task. Please provide a small reproduction if you want me to investigate more.

**Comment by manuzhang** [comment]
Indeed, thanks
