### ISSUE TITLE
Compilation should fail when `@silent` does not suppress anything

### ISSUE THREAD

**Issue by Daenyth** [ghik/silencer#28]
Currently it seems like `@silent` can be added anywhere, even if it's not needed. This is particularly bothersome when it's applied to classes; a code change could fix the initial warning that's being ignored, but leave `@silent` in place, opening up accidental regression on further code changes.

**Comment by ghik** [comment]
That's an interesting idea. I don't think we can make what you propose the default behavior - it could break existing projects. However, we might hide it behind a flag.

**Comment by SethTisue** [comment]
breaking existing projects seems okay to me here. the existing projects are likely to want to remove those stale annotations

**Comment by ghik** [comment]
@SethTisue what is the last compiler phase that can emit warnings?
Checking whether `@silent` has actually silenced something must happen after that phase.

**Comment by SethTisue** [comment]
even the `jvm` phase can emit warnings. (I don't call it the "last" phase because there's also `terminal`)

**Comment by ghik** [comment]
IMO, another reason to **not** enable this checking by default is that it may be problematic in cross-compiled projects where e.g. Scala 2.12 emits a warning but Scala 2.11 doesn't.

**Comment by ghik** [comment]
Fixed in 1.4.0
