### ISSUE TITLE
False positive with "-P:silencer:checkUnused" flag and default parameters

### ISSUE THREAD

**Issue by kamilkloch** [ghik/silencer#29]
`-P:silencer:checkUnused` flag  enabled.
The following code
```scala
class A(b: B = DeprecatedBImpl)
```
compiles with a deprecation warning `object DeprecatedBImpl in object A is deprecated`. Adding `@silent` flag 
```scala
class A(b: B = DeprecatedBImpl: @silent)
```
causes the following compilation error: `this @silent annotation does not suppress any warnings`.

**Comment by ghik** [comment]
Fixed in 1.4.1, it will be available as soon as Maven Central catches up.
