### ISSUE TITLE
Usage of `silencer:globalFilters` in Maven projects.

### ISSUE THREAD

**Issue by vamsikt** [ghik/silencer#39]
How can we use `silencer:globalFilters` in maven projects?

```-P:silencer:globalFilters=<semicolon separated message regexes>```

I am trying to pass the silencer flag option using `scala-maven-plugin`
```
<configuration>
<args>
<arg>-P:silencer:globalFilters=Unused import</arg>
<arg> ....<arg>
<arg>-Xfatal-warnings</arg>
<arg>-Ywarn-unused-import</arg>
</args>
</configuration>
```

**Comment by ghik** [comment]
I haven't used `scala-maven-plugin`. Can you explain what doesn't work?

**Comment by vamsikt** [comment]
@ghik I got a compilation error [scala-maven-plugin](https://github.com/davidB/scala-maven-plugin)
`bad option: -P:silencer:globalFilters=Unused import`.

also used in conjunction with [addScalacArgs](http://davidb.github.io/scala-maven-plugin/cc-mojo.html#addScalacArgs) but got same error.
`          <addScalacArgs>-P:silencer:checkUnused=Unused import</addScalacArgs>
`

**Comment by SethTisue** [comment]
perhaps scala-maven-plugin has a problem with spaces in arguments, rather than there being a problem with silencer specifically?

**Comment by vamsikt** [comment]
@SethTisue got the same error when used `checkUnused`option.

` <addScalacArgs>-P:silencer:checkUnused</addScalacArgs>
`
Error:
`bad option: -P:silencer:checkUnused`

**Comment by SethTisue** [comment]
okay, then it looks to me like a symptom of the silencer plugin not being enabled properly. if silencer isn't operating at all, then scalac will reject any `-P:silencer:...` flag

do you have any evidence that you have silencer working properly to begin with, _before_ attempting to customize its behavior with `-P:silencer:...`?

**Comment by vamsikt** [comment]
Did not get you what you meant by
>silencer plugin not being enabled properly?

I added the silencer plugin dependencies to the maven `pom.xml`.

**Comment by SethTisue** [comment]
> I added the silencer plugin dependencies to the maven pom.xml

but did you do it correctly? is silencer working with its default settings? that's what we need to determine, in order to know whether there's something specific to `globalFilters` here or not. (I suspect there isn't.)

**Comment by vamsikt** [comment]
Yes, I can import silencer API's and use annotations in my project.
`  @silent def someMethod() = {  }
`

**Comment by SethTisue** [comment]
> Yes, I can import silencer API's and use annotations in my project.

That doesn't prove that the compiler plugin is actually operating. It merely proves that you have it on the classpath.

Do you have any evidence that the plugin is actually operating?

**Comment by SethTisue** [comment]
Note that this repo's README includes the following Gradle snippet:

```
tasks.withType(ScalaCompile) {
    scalaCompileOptions.additionalParameters =
            configurations.scalacPlugin.collect { "-Xplugin:" + it.absolutePath }
}
```

have you done anything comparable in your Maven build?

**Comment by vamsikt** [comment]
> To expand on what I said about `-Xplugin`, note that this repo's README includes the following Gradle snippet:
> 
> ```
> tasks.withType(ScalaCompile) {
>     scalaCompileOptions.additionalParameters =
>             configurations.scalacPlugin.collect { "-Xplugin:" + it.absolutePath }
> }
> ```
> 
> have you done anything comparable in your Maven build?

No,I'll check that.

**Comment by jozic** [comment]
this worked for me (Scala 2.12.10)

```xml
<plugin>
                    <groupId>net.alchim31.maven</groupId>
                    <artifactId>scala-maven-plugin</artifactId>
                    <version>3.4.6</version>
                    <configuration>
                        <scalaCompatVersion>${scala.binary.version}</scalaCompatVersion>
                        <scalaVersion>${scala.version}</scalaVersion>
                        <failOnMultipleScalaVersions>true</failOnMultipleScalaVersions>
                        <args>
                            <arg>-Xlint</arg>
                            <arg>-deprecation</arg>
                            <arg>-unchecked</arg>
                            <arg>-feature</arg>
                            <arg>-language:postfixOps</arg>
                            <arg>-language:implicitConversions</arg>
                            <arg>-language:higherKinds</arg>
                            <arg>-Xfatal-warnings</arg>
                            <arg>-Ywarn-unused</arg>
                            <arg>-Ywarn-unused-import</arg>
                            <arg>-Ywarn-inaccessible</arg>
                            <arg>-Ywarn-dead-code</arg>
                            <arg>-Ypartial-unification</arg>
                            <arg>-P:silencer:globalFilters=Unused import</arg>
                        </args>
                        <jvmArgs>
                            <jvmArg>-Xmx4g</jvmArg>
                        </jvmArgs>
                        <compilerPlugins>
                            <compilerPlugin>
                                <groupId>com.github.ghik</groupId>
                                <artifactId>silencer-plugin_${scala.version}</artifactId>
                                <version>${silencer.plugin.version}</version>
                            </compilerPlugin>
                        </compilerPlugins>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.scala-lang</groupId>
                            <artifactId>scala-library</artifactId>
                            <version>${scala.version}</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>scala-compile-first</id>
                            <phase>process-resources</phase>
                            <goals>
                                <goal>add-source</goal>
                                <goal>compile</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>scala-test-compile</id>
                            <phase>process-test-resources</phase>
                            <goals>
                                <goal>testCompile</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
```

though I failed to find a way to specify some particular imported class to be ignored

**Comment by SethTisue** [comment]
ah, `<compilerPlugin>`, that must handle the `-Xplugin` thing for you :+1:

**Comment by vamsikt** [comment]
Yes, that solves that issue.
Thank you @jozic @SethTisue. 
Perhaps it is better to add these instructions to the `README`.
