### ISSUE TITLE
cannot suppress scala 2.12.2 -Ywarn-unused:params for Scala.js js.native method

### ISSUE THREAD

**Issue by kwisatzook** [ghik/silencer#4]
See JsCryptoNative.getRandomValues at the bottom. @silent doesn't seem to work no matter where I put it.

```scala
import scala.scalajs.js
import scala.scalajs.js.annotation._
import scala.scalajs.js.typedarray.ArrayBufferView

import com.github.ghik.silencer.silent

@js.native
@JSGlobalScope
object WindowGlobalScope extends js.Object {
  def window: js.UndefOr[JsWindowNative] = js.native
}

@js.native
trait JsWindowNative extends js.Object {
  def crypto: js.UndefOr[JsCryptoNative] = js.native
  def msCrypto: js.UndefOr[JsCryptoNative] = js.native
}

@js.native
@silent
trait JsCryptoNative extends js.Object {
  @silent
  def getRandomValues( // linter:ignore UnusedParameter
      @silent t: ArrayBufferView @silent
    ): Unit @silent = js.native
}
```

Any idea as to why and any suggestions on a workaround?
Much thanks.

**Comment by ghik** [comment]
Hello @kwisatzook 

I can't reproduce your problem. For me putting `@silent` annotation on the parameter works just fine.

Here's a the project where I tried to reproduce it: [scalajs-silencer-bug.zip](https://github.com/ghik/silencer/files/1127899/scalajs-silencer-bug.zip)

**Comment by kwisatzook** [comment]
Ah, thanks. It wasn't set up properly. Even though the plugin was downloaded and the library was available, the compiler plugin wasn't enabled because the setting didn't propagate to the cross project. I figured out how to make that happen.
Thanks.
