### ISSUE TITLE
Silence warnings based on line content

### ISSUE THREAD

**Issue by ghik** [ghik/silencer#42]
This would be particularly useful in order to silence "unused import" warnings (#30) based on what's being imported, e.g. with regex-based compiler option like:

`-P:silencer:lineContentFilters=import scala\.collection\.compat\._`

**Comment by tjarvstrand** [comment]
This would be great! We get a lot of false positives for unused import when using implicits

**Comment by ghik** [comment]
Fixed in 1.5.0

**Comment by tjarvstrand** [comment]
Sweet!

**Comment by som-snytt** [comment]
@tjarvstrand There should be zero false positives in recent Scala versions. If you're using macros that require imports but don't emit code that uses them, that's a different kettle of fish.

**Comment by tjarvstrand** [comment]
We mostly get them in code related to pureconfig's automatic derivation which I think uses macros so maybe the problem is in there somewhere

**Comment by som-snytt** [comment]
@tjarvstrand thanks for the feedback.
