### ISSUE TITLE
Extremely slow compilation when silencer plugin enabled

### ISSUE THREAD

**Issue by igrocki** [ghik/silencer#45]
Next lines of code compiles at least 25 seconds when silencer plugin enabled and just 1 seconds with disabled plugin
```scala
import sttp.tapir._

case class Foo(a: Int)

object Main extends App {
  val a = implicitly[Schema[Foo]]
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 1s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 2s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 6s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 16s with silencer and 1s without
    .modify(_.a)(_.description("foo")) // 25s with silencer and 1s without
}
```
where `modify` - is macro function from [tapir](https://github.com/softwaremill/tapir) library.

Repo with simple reproducer: https://github.com/igrocki/slow-silencer-tapir

I found ugly workaround: breaking method chain into two or more chains like:

```scala
val a = implicitly[Schema[Foo]]
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 

val b = a.modify(_.a)(_.description("foo"))
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
    .modify(_.a)(_.description("foo")) 
```

**Comment by SethTisue** [comment]
very nice catch!! 👏 thank you for isolating and reporting

**Comment by SethTisue** [comment]
fwiw, https://github.com/scala/scala/pull/8373 doesn't seem to have this problem (tested with 2.13.2-bin-59cf05f-SNAPSHOT)

**Comment by ghik** [comment]
This is caused by tapir's macros which seem to blow up exponentially. Silencer looks for `@silent` annotations in both macro expandees and macro expansions. In the reproduction provided by @igrocki (huge thanks!) silencer has to traverse 1659690482(!) trees. But when I disabled looking for `@silent` annotation in macro expansions, it drastically went down to just 569 trees and compilation time dropped accordingly.

I probably could just ignore macro expansions as it's very unlikely that someone would put `@silent` annotations in macro generated code, but I'm not sure if it won't break something.

**Comment by ghik** [comment]
Ok, I've decided to go on and ignore macro expansions by default. I've also introduced an option to bring back the old behaviour (`-P:silencer:searchMacroExpansions`).
These changes are available in freshly released 1.6.0

**Comment by SethTisue** [comment]
> This is caused by tapir's macros which seem to blow up exponentially

I wonder if tapir's maintainers know about that.

**Comment by adamw** [comment]
@SethTisue yes :) https://github.com/softwaremill/tapir/issues/455
