### ISSUE TITLE
Support Java @SuppressWarnings annotation?

### ISSUE THREAD

**Issue by lihaoyi-databricks** [ghik/silencer#46]
More a feature request than a bug, but could we make Silencer also support `@SuppressWarnings`? It comes built in with the JDK, doesn't need an import, and has a slightly more meaningful name than just `@silent`

**Comment by ghik** [comment]
I agree with [Lukas' comment](https://github.com/scala/scala/pull/8373#issuecomment-594458849) on this. Let's see what solution will be chosen in the compiler and then I might backport it to silencer.

**Comment by lihaoyi-databricks** [comment]
Superseded by https://github.com/ghik/silencer/issues/50
