### ISSUE TITLE
Can CrossBuilding full for silencer-lib be avoided?

### ISSUE THREAD

**Issue by jrudolph** [ghik/silencer#59]
Since silencer-lib is not provided for all minor Scala versions, matching Scala version and silencer-lib version can be quite a hassle in CI environments where the Scala library can be overwritten from the outside.

Is there a good reason for the weird publishing (i.e. only for the library, for the compiler plugin it is expected)?

**Comment by ghik** [comment]
There's no need to fully-cross-build `silencer-lib` but I don't understand what would be the benefit of that if `silencer-plugin` still has to be cross built like that. What's the point of using `silencer-lib` without `silencer-plugin`?

**Comment by jrudolph** [comment]
> There's no need to fully-cross-build `silencer-lib` but I don't understand what would be the benefit of that if `silencer-plugin` still has to be cross built like that. What's the point of using `silencer-lib` without `silencer-plugin`?

Ah right, that's a good point, so you might need different versions of silencer anyway if you want to support a wider set of Scala versions. I guess then there's nothing to see here, sorry for the noise...
