### ISSUE TITLE
Support for projects using gradle scala plugin

### ISSUE THREAD

**Issue by CalumMcCall** [ghik/silencer#6]
I'm using the [Gradle Scala Plugin](https://github.com/saturday06/gradle-android-scala-plugin). What would be the easiest way to using silencer in such a project? I've had a look at the docs for both projects and I don't see an obvious way. Is migrating to SBT the only way?

**Comment by ghik** [comment]
Hello, I'm on holidays and I can't check how it's done exactly in Gradle Scala plugin but it should be easy - silencer is a Scala compiler plugin so you just need to find out how to configure compiler plugins in Gradle. 

Even if Gradle Scala plugin doesn't support compiler plugins natively, adding a compiler plugin should be as easy as adding a command line option to scalac.

So either way, please look for general information on how to configure Scala compiler plugins.

**Comment by CalumMcCall** [comment]
Thanks for getting back to me so quickly. That's really useful info, I wasn't sure if compiler plugins had to be packaged for a particular build tool -- good to know they aren't. I'll have a look at the docs.
