### ISSUE TITLE
Publish for Scala 2.12.18 and 2.13.11, please?

### ISSUE THREAD

**Issue by SethTisue** [ghik/silencer#79]
2.12.18 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-12-18-release-planning/6089/9

2.13.11 JARs are on Maven Central, as per https://contributors.scala-lang.org/t/scala-2-13-11-release-planning/6088/11

**Comment by SethTisue** [comment]
Broadened to include 2.13.11.

**Comment by ghik** [comment]
I hit [this issue](https://github.com/ghik/silencer/actions/runs/5157818640/jobs/9290749938) which I have currently no patience to debug. I will come later to that.

**Comment by dongjoon-hyun** [comment]
Hi, Roman. According to the log, is the following the root cause of failure?
```
[info] gpg: no default secret key: No secret key
[info] gpg: signing failed: No secret key
```

**Comment by ghik** [comment]
Worked after recreating GPG secrets (the previous key most likely expired).

**Comment by mkurz** [comment]
@ghik I think you made a mistake. The tag you pushed is 1.7.13 but the release on maven central is 1.17.13:
* https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.12.17/
* https://repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.12.18/

Maybe a typo?

**Comment by ghik** [comment]
@mkurz yeah, will be fixed soon

**Comment by dongjoon-hyun** [comment]
Thank you so much, @ghik !

**Comment by dongjoon-hyun** [comment]
Also cc @LuciferYang, too
